version: "3.8"

services:
  typesense:
    image: typesense/typesense:27.0
    ports:
      - target: 8108
        published: 8108
        protocol: tcp
    volumes:
      - ./tmp:/data
    command: "--data-dir /data --api-key=$TYPESENSE_API_KEY --enable-cors"
